include ./themes/everforest.conf
# include ./themes/dracula.conf
# include ./themes/Cobalt2.conf
# include ./themes/Github.conf
# include ./themes/gruvbox_light.conf
# include ./themes/gruvbox_dark.conf

line_height 1.12

