set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-fzf'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# change prefix 
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix 

unbind C-/
bind-key -n C-/ send-keys C-/

# for config reload 
unbind r
bind r source-file ~/.tmux.conf
# bind-key C-t source-file ~/.tmux.conf \; display "Config Reloaded !"

# start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
set -g repeat-time 0
set -g default-terminal "screen-256color"

set -g mouse on

# maybe to find sessions
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind -r m resize-pane -Z

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set-option -g display-time 2000 # by default, status msg disappears in the blink of eye (750 ms)
set-option -g display-panes-time 2000 # by default, pane number disappears in 1s
set-option -g history-limit 40000 # maximum number of lines held in window history - crank it up from 2k default
set-option -g lock-after-time 3600 # lock the session after 60 mins of inactivity. Sometimes, it is good to protect your screen to make sure other's can't see enough
set-option -wg automatic-rename off # default names are too vauge to see. Let me name it. 

set -g base-index 1
set-window-option -g pane-base-index 1 # pane index will start with 1
set-option -g renumber-windows on

# Pane: vim style movements 
bind-key -r h select-pane -L # go left
bind-key -r j select-pane -D # go down
bind-key -r l select-pane -R # go right
bind-key -r k select-pane -U # go up

# Pane: Arrow movements 
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

# Window: Movements 
bind-key L last-window 
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+ 

# word separators for automatic word selection 
set-window-option -g word-separators ' @"=()[]' # default => ' -_@'.

# tmux adds a short, almost imperceptible display between the commands that can cause funny behaviour when running vim inside tmux. 
set-option -s escape-time 0 

# command prompt movements: within the tmux command prompt and the command prompt is accessed using <P>: (in the status line)
set-option -g status-keys vi

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

bind-key -n 'C-\' if-shell '[ "$(tmux list panes | wc -l | bc)" = 1]' {
    split-window -c '#{pane_current_path}'
} {
    if-shell '[ -n "$(tmux list panes -F ''#F'' | grep Z)" ]' {
        select-pane -t:.-
    } {
        resize-pane -Z -t1
    }
}

# initialize tmux plugin manager (keep this at very bottom)
run '~/.tmux/plugins/tpm/tpm'
